-- Snitch: bootstrap completo para um projeto Supabase NOVO / banco vazio.
-- Este script inclui as tabelas atuais do ORM + cache híbrido.
-- Execute UMA vez no SQL Editor do Supabase (como postgres).
-- NÃO execute sobre banco existente: use as migrações Alembic para upgrades.
-- Sem acesso direto de anon/authenticated/service_role ao banco: a API pública
-- passa pelo FastAPI, com DATABASE_URL disponível somente no servidor.

BEGIN;

CREATE TABLE public.legislaturas (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  camara_id integer NOT NULL UNIQUE,
  numero integer NOT NULL UNIQUE,
  data_inicio varchar(50),
  data_fim varchar(50),
  ano_inicio integer,
  ano_fim integer
);

CREATE TABLE public.deputados (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  camara_id integer NOT NULL UNIQUE,
  nome_parlamentar varchar(255) NOT NULL,
  nome_civil varchar(255),
  sigla_partido varchar(50),
  uf varchar(10),
  url_foto varchar(500),
  situacao varchar(100),
  condicao_eleitoral varchar(100),
  descricao_status text,
  email varchar(255),
  legislatura integer,
  gabinete_predio varchar(50),
  gabinete_sala varchar(50),
  gabinete_andar varchar(50),
  gabinete_telefone varchar(50),
  data_nascimento varchar(50),
  municipio_nascimento varchar(100),
  uf_nascimento varchar(10),
  escolaridade varchar(100),
  rede_social json,
  url_website varchar(500),
  uri varchar(500),
  dados_raw json,
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.mandatos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deputado_id integer NOT NULL REFERENCES public.deputados(id) ON DELETE CASCADE,
  legislatura_id integer,
  legislatura_numero integer,
  cargo varchar(100) DEFAULT 'Deputado Federal',
  sigla_partido varchar(50),
  uf varchar(10),
  situacao varchar(100),
  condicao_eleitoral varchar(100),
  data_inicio varchar(50),
  data_fim varchar(50),
  dados_raw json
);

CREATE TABLE public.filiacoes_partidarias (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deputado_id integer NOT NULL REFERENCES public.deputados(id) ON DELETE CASCADE,
  sigla_partido varchar(50) NOT NULL,
  nome_partido varchar(150),
  data_inicio varchar(50),
  data_fim varchar(50),
  fonte varchar(100) DEFAULT 'Câmara dos Deputados'
);

CREATE TABLE public.deputado_historico (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deputado_id integer NOT NULL REFERENCES public.deputados(id) ON DELETE CASCADE,
  data_hora varchar(50),
  sigla_partido varchar(50),
  situacao varchar(100),
  condicao_eleitoral varchar(100),
  descricao_status text,
  legislatura integer
);

CREATE TABLE public.proposicoes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  camara_id integer NOT NULL UNIQUE,
  sigla_tipo varchar(50) NOT NULL,
  numero integer NOT NULL,
  ano integer NOT NULL,
  ementa text,
  ementa_detalhada text,
  data_apresentacao varchar(50),
  situacao varchar(150),
  descricao_situacao text,
  regime varchar(100),
  despacho text,
  orgao_atual varchar(100),
  url_inteiro_teor varchar(500),
  uri varchar(500),
  dados_raw json,
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.proposicao_autores (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  proposicao_id integer NOT NULL REFERENCES public.proposicoes(id) ON DELETE CASCADE,
  deputado_id integer,
  nome_autor varchar(255) NOT NULL,
  tipo_autor varchar(100),
  ordem_autoria integer DEFAULT 1,
  proponente boolean DEFAULT false,
  uri_autor varchar(500)
);

CREATE TABLE public.temas (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  camara_id integer UNIQUE,
  nome varchar(150) NOT NULL UNIQUE
);

CREATE TABLE public.proposicao_temas (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  proposicao_id integer NOT NULL REFERENCES public.proposicoes(id) ON DELETE CASCADE,
  tema_id integer NOT NULL REFERENCES public.temas(id) ON DELETE CASCADE,
  relevancia integer DEFAULT 0
);

CREATE TABLE public.tramitacoes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  proposicao_id integer NOT NULL REFERENCES public.proposicoes(id) ON DELETE CASCADE,
  data_hora varchar(50),
  sequencia integer NOT NULL DEFAULT 1,
  descricao_tramitacao varchar(255),
  despacho text,
  orgao varchar(100),
  situacao varchar(150),
  regime varchar(100),
  url_documento varchar(500)
);

CREATE TABLE public.votacoes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  camara_id varchar(100) NOT NULL UNIQUE,
  data_hora_registro varchar(50),
  descricao text NOT NULL,
  resultado varchar(255),
  aprovada boolean,
  orgao varchar(100),
  evento_camara_id integer,
  placar_sim integer DEFAULT 0,
  placar_nao integer DEFAULT 0,
  placar_abstencao integer DEFAULT 0,
  placar_obstrucao integer DEFAULT 0,
  uri varchar(500),
  dados_raw json,
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.votacao_proposicoes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  votacao_id integer NOT NULL REFERENCES public.votacoes(id) ON DELETE CASCADE,
  proposicao_id integer NOT NULL REFERENCES public.proposicoes(id) ON DELETE CASCADE,
  tipo_relacao varchar(100) DEFAULT 'Votação relacionada à proposição',
  descricao text
);

CREATE TABLE public.votacao_orientacoes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  votacao_id integer NOT NULL REFERENCES public.votacoes(id) ON DELETE CASCADE,
  bancada varchar(100) NOT NULL,
  orientacao_voto varchar(50) NOT NULL
);

CREATE TABLE public.votos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  votacao_id integer NOT NULL REFERENCES public.votacoes(id) ON DELETE CASCADE,
  deputado_id integer NOT NULL REFERENCES public.deputados(id) ON DELETE CASCADE,
  tipo_voto varchar(50) NOT NULL,
  data_hora varchar(50),
  sigla_partido_momento varchar(50),
  uf_momento varchar(10)
);

CREATE TABLE public.eventos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  camara_id integer NOT NULL UNIQUE,
  data_inicio varchar(50),
  data_fim varchar(50),
  tipo varchar(100),
  descricao text,
  situacao varchar(100),
  local varchar(255),
  uri varchar(500),
  dados_raw json
);

CREATE TABLE public.evento_deputados (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  evento_id integer NOT NULL REFERENCES public.eventos(id) ON DELETE CASCADE,
  deputado_id integer NOT NULL REFERENCES public.deputados(id) ON DELETE CASCADE
);

CREATE TABLE public.instituicoes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar(255) NOT NULL,
  sigla varchar(50),
  tipo varchar(50) NOT NULL,
  poder varchar(50) NOT NULL,
  esfera varchar(50) NOT NULL,
  nivel_federativo varchar(50) NOT NULL,
  codigo_externo varchar(100),
  natureza_juridica varchar(150),
  descricao text,
  site_oficial varchar(500),
  fonte varchar(150) NOT NULL DEFAULT 'SIORG / dados.gov.br',
  url_fonte varchar(500),
  ativo boolean DEFAULT true,
  dados_raw json,
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.relacoes_institucionais (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instituicao_origem_id integer NOT NULL REFERENCES public.instituicoes(id) ON DELETE CASCADE,
  instituicao_destino_id integer NOT NULL REFERENCES public.instituicoes(id) ON DELETE CASCADE,
  tipo_relacao varchar(50) NOT NULL,
  data_inicio varchar(50),
  data_fim varchar(50),
  descricao text,
  fonte varchar(150) DEFAULT 'Estrutura Oficial',
  url_fonte varchar(500),
  dados_raw json
);

CREATE TABLE public.cargos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instituicao_id integer NOT NULL REFERENCES public.instituicoes(id) ON DELETE CASCADE,
  nome varchar(150) NOT NULL,
  tipo varchar(50),
  fonte varchar(100) DEFAULT 'Oficial'
);

CREATE TABLE public.ocupacoes_cargo (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cargo_id integer NOT NULL REFERENCES public.cargos(id) ON DELETE CASCADE,
  pessoa_id integer,
  nome_ocupante varchar(255) NOT NULL,
  data_inicio varchar(50),
  data_fim varchar(50),
  fonte varchar(100) DEFAULT 'Oficial'
);

CREATE TABLE public.sync_runs (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo varchar(50) NOT NULL,
  iniciado_em timestamptz DEFAULT now(),
  finalizado_em timestamptz,
  status varchar(20) DEFAULT 'RUNNING',
  registros_processados integer DEFAULT 0,
  erro text
);

CREATE TABLE public.official_cache (
  cache_key varchar(200) PRIMARY KEY,
  source varchar(50) NOT NULL,
  source_url varchar(500) NOT NULL,
  payload json NOT NULL,
  fetched_at timestamptz NOT NULL,
  expires_at timestamptz NOT NULL
);

CREATE INDEX ix_legislaturas_id ON public.legislaturas (id);
CREATE UNIQUE INDEX ix_legislaturas_camara_id ON public.legislaturas (camara_id);
CREATE UNIQUE INDEX ix_legislaturas_numero ON public.legislaturas (numero);
CREATE INDEX ix_deputados_id ON public.deputados (id);
CREATE UNIQUE INDEX ix_deputados_camara_id ON public.deputados (camara_id);
CREATE INDEX ix_deputados_nome_parlamentar ON public.deputados (nome_parlamentar);
CREATE INDEX ix_deputados_sigla_partido ON public.deputados (sigla_partido);
CREATE INDEX ix_deputados_uf ON public.deputados (uf);
CREATE INDEX ix_deputados_situacao ON public.deputados (situacao);
CREATE INDEX ix_deputados_legislatura ON public.deputados (legislatura);
CREATE INDEX ix_mandatos_id ON public.mandatos (id);
CREATE INDEX ix_mandatos_deputado_id ON public.mandatos (deputado_id);
CREATE INDEX ix_mandatos_legislatura_id ON public.mandatos (legislatura_id);
CREATE INDEX ix_mandatos_legislatura_numero ON public.mandatos (legislatura_numero);
CREATE INDEX ix_mandatos_sigla_partido ON public.mandatos (sigla_partido);
CREATE INDEX ix_mandatos_uf ON public.mandatos (uf);
CREATE INDEX ix_mandatos_situacao ON public.mandatos (situacao);
CREATE INDEX ix_filiacoes_partidarias_id ON public.filiacoes_partidarias (id);
CREATE INDEX ix_filiacoes_partidarias_deputado_id ON public.filiacoes_partidarias (deputado_id);
CREATE INDEX ix_filiacoes_partidarias_sigla_partido ON public.filiacoes_partidarias (sigla_partido);
CREATE INDEX ix_deputado_historico_id ON public.deputado_historico (id);
CREATE INDEX ix_deputado_historico_deputado_id ON public.deputado_historico (deputado_id);
CREATE INDEX ix_proposicoes_id ON public.proposicoes (id);
CREATE UNIQUE INDEX ix_proposicoes_camara_id ON public.proposicoes (camara_id);
CREATE INDEX ix_proposicoes_sigla_tipo ON public.proposicoes (sigla_tipo);
CREATE INDEX ix_proposicoes_numero ON public.proposicoes (numero);
CREATE INDEX ix_proposicoes_ano ON public.proposicoes (ano);
CREATE INDEX ix_proposicoes_data_apresentacao ON public.proposicoes (data_apresentacao);
CREATE INDEX ix_proposicoes_situacao ON public.proposicoes (situacao);
CREATE INDEX ix_proposicao_autores_id ON public.proposicao_autores (id);
CREATE INDEX ix_proposicao_autores_proposicao_id ON public.proposicao_autores (proposicao_id);
CREATE INDEX ix_proposicao_autores_deputado_id ON public.proposicao_autores (deputado_id);
CREATE INDEX ix_temas_id ON public.temas (id);
CREATE UNIQUE INDEX ix_temas_camara_id ON public.temas (camara_id);
CREATE UNIQUE INDEX ix_temas_nome ON public.temas (nome);
CREATE INDEX ix_proposicao_temas_id ON public.proposicao_temas (id);
CREATE INDEX ix_proposicao_temas_proposicao_id ON public.proposicao_temas (proposicao_id);
CREATE INDEX ix_proposicao_temas_tema_id ON public.proposicao_temas (tema_id);
CREATE INDEX ix_tramitacoes_id ON public.tramitacoes (id);
CREATE INDEX ix_tramitacoes_proposicao_id ON public.tramitacoes (proposicao_id);
CREATE INDEX ix_votacoes_id ON public.votacoes (id);
CREATE UNIQUE INDEX ix_votacoes_camara_id ON public.votacoes (camara_id);
CREATE INDEX ix_votacoes_data_hora_registro ON public.votacoes (data_hora_registro);
CREATE INDEX ix_votacao_proposicoes_id ON public.votacao_proposicoes (id);
CREATE INDEX ix_votacao_proposicoes_votacao_id ON public.votacao_proposicoes (votacao_id);
CREATE INDEX ix_votacao_proposicoes_proposicao_id ON public.votacao_proposicoes (proposicao_id);
CREATE INDEX ix_votacao_orientacoes_id ON public.votacao_orientacoes (id);
CREATE INDEX ix_votacao_orientacoes_votacao_id ON public.votacao_orientacoes (votacao_id);
CREATE INDEX ix_votos_id ON public.votos (id);
CREATE INDEX ix_votos_votacao_id ON public.votos (votacao_id);
CREATE INDEX ix_votos_deputado_id ON public.votos (deputado_id);
CREATE INDEX ix_votos_tipo_voto ON public.votos (tipo_voto);
CREATE INDEX ix_eventos_id ON public.eventos (id);
CREATE UNIQUE INDEX ix_eventos_camara_id ON public.eventos (camara_id);
CREATE INDEX ix_eventos_data_inicio ON public.eventos (data_inicio);
CREATE INDEX ix_evento_deputados_id ON public.evento_deputados (id);
CREATE INDEX ix_evento_deputados_evento_id ON public.evento_deputados (evento_id);
CREATE INDEX ix_evento_deputados_deputado_id ON public.evento_deputados (deputado_id);
CREATE INDEX ix_instituicoes_id ON public.instituicoes (id);
CREATE INDEX ix_instituicoes_nome ON public.instituicoes (nome);
CREATE INDEX ix_instituicoes_sigla ON public.instituicoes (sigla);
CREATE INDEX ix_instituicoes_tipo ON public.instituicoes (tipo);
CREATE INDEX ix_instituicoes_poder ON public.instituicoes (poder);
CREATE INDEX ix_instituicoes_esfera ON public.instituicoes (esfera);
CREATE INDEX ix_instituicoes_nivel_federativo ON public.instituicoes (nivel_federativo);
CREATE INDEX ix_instituicoes_codigo_externo ON public.instituicoes (codigo_externo);
CREATE INDEX ix_relacoes_institucionais_id ON public.relacoes_institucionais (id);
CREATE INDEX ix_relacoes_institucionais_instituicao_origem_id ON public.relacoes_institucionais (instituicao_origem_id);
CREATE INDEX ix_relacoes_institucionais_instituicao_destino_id ON public.relacoes_institucionais (instituicao_destino_id);
CREATE INDEX ix_relacoes_institucionais_tipo_relacao ON public.relacoes_institucionais (tipo_relacao);
CREATE INDEX ix_cargos_id ON public.cargos (id);
CREATE INDEX ix_cargos_instituicao_id ON public.cargos (instituicao_id);
CREATE INDEX ix_ocupacoes_cargo_id ON public.ocupacoes_cargo (id);
CREATE INDEX ix_ocupacoes_cargo_cargo_id ON public.ocupacoes_cargo (cargo_id);
CREATE INDEX ix_ocupacoes_cargo_pessoa_id ON public.ocupacoes_cargo (pessoa_id);
CREATE INDEX ix_sync_runs_id ON public.sync_runs (id);
CREATE INDEX ix_official_cache_source ON public.official_cache (source);

-- Índices adicionais para consultas históricas e comparação.
CREATE INDEX ix_votos_deputado_votacao ON public.votos (deputado_id, votacao_id);
CREATE INDEX ix_votacao_proposicoes_votacao ON public.votacao_proposicoes (votacao_id, proposicao_id);
CREATE INDEX ix_proposicao_temas_proposicao ON public.proposicao_temas (proposicao_id, tema_id);
CREATE INDEX ix_official_cache_expires ON public.official_cache (expires_at);

-- Conservar compatibilidade com a linha atual de migrações Alembic.
CREATE TABLE public.alembic_version (version_num varchar(32) NOT NULL PRIMARY KEY);
INSERT INTO public.alembic_version(version_num) VALUES ('a64b8f27c901');

-- Os dados são públicos pelo FastAPI, NÃO pelo Data API do Supabase.
-- Esse bloqueio é intencional, inclusive para tabelas de auditoria e cache.
ALTER TABLE public.legislaturas ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.legislaturas FROM anon, authenticated, service_role;
ALTER TABLE public.deputados ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.deputados FROM anon, authenticated, service_role;
ALTER TABLE public.mandatos ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.mandatos FROM anon, authenticated, service_role;
ALTER TABLE public.filiacoes_partidarias ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.filiacoes_partidarias FROM anon, authenticated, service_role;
ALTER TABLE public.deputado_historico ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.deputado_historico FROM anon, authenticated, service_role;
ALTER TABLE public.proposicoes ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.proposicoes FROM anon, authenticated, service_role;
ALTER TABLE public.proposicao_autores ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.proposicao_autores FROM anon, authenticated, service_role;
ALTER TABLE public.temas ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.temas FROM anon, authenticated, service_role;
ALTER TABLE public.proposicao_temas ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.proposicao_temas FROM anon, authenticated, service_role;
ALTER TABLE public.tramitacoes ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.tramitacoes FROM anon, authenticated, service_role;
ALTER TABLE public.votacoes ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.votacoes FROM anon, authenticated, service_role;
ALTER TABLE public.votacao_proposicoes ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.votacao_proposicoes FROM anon, authenticated, service_role;
ALTER TABLE public.votacao_orientacoes ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.votacao_orientacoes FROM anon, authenticated, service_role;
ALTER TABLE public.votos ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.votos FROM anon, authenticated, service_role;
ALTER TABLE public.eventos ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.eventos FROM anon, authenticated, service_role;
ALTER TABLE public.evento_deputados ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.evento_deputados FROM anon, authenticated, service_role;
ALTER TABLE public.instituicoes ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.instituicoes FROM anon, authenticated, service_role;
ALTER TABLE public.relacoes_institucionais ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.relacoes_institucionais FROM anon, authenticated, service_role;
ALTER TABLE public.cargos ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.cargos FROM anon, authenticated, service_role;
ALTER TABLE public.ocupacoes_cargo ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.ocupacoes_cargo FROM anon, authenticated, service_role;
ALTER TABLE public.sync_runs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.sync_runs FROM anon, authenticated, service_role;
ALTER TABLE public.official_cache ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.official_cache FROM anon, authenticated, service_role;
ALTER TABLE public.alembic_version ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.alembic_version FROM anon, authenticated, service_role;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  REVOKE ALL ON TABLES FROM anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  REVOKE ALL ON SEQUENCES FROM anon, authenticated, service_role;

COMMIT;
