"""historical_deputies_and_governo_models

Revision ID: 30d164bc1533
Revises: fe8661aa8f62
Create Date: 2026-09-24 11:59:00.598051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30d164bc1533'
down_revision: Union[str, Sequence[str], None] = 'fe8661aa8f62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instituicoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('sigla', sa.String(length=50), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('poder', sa.String(length=50), nullable=False),
    sa.Column('esfera', sa.String(length=50), nullable=False),
    sa.Column('nivel_federativo', sa.String(length=50), nullable=False),
    sa.Column('codigo_externo', sa.String(length=100), nullable=True),
    sa.Column('natureza_juridica', sa.String(length=150), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('site_oficial', sa.String(length=500), nullable=True),
    sa.Column('fonte', sa.String(length=150), nullable=False),
    sa.Column('url_fonte', sa.String(length=500), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('dados_raw', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instituicoes_codigo_externo'), 'instituicoes', ['codigo_externo'], unique=False)
    op.create_index(op.f('ix_instituicoes_esfera'), 'instituicoes', ['esfera'], unique=False)
    op.create_index(op.f('ix_instituicoes_id'), 'instituicoes', ['id'], unique=False)
    op.create_index(op.f('ix_instituicoes_nivel_federativo'), 'instituicoes', ['nivel_federativo'], unique=False)
    op.create_index(op.f('ix_instituicoes_nome'), 'instituicoes', ['nome'], unique=False)
    op.create_index(op.f('ix_instituicoes_poder'), 'instituicoes', ['poder'], unique=False)
    op.create_index(op.f('ix_instituicoes_sigla'), 'instituicoes', ['sigla'], unique=False)
    op.create_index(op.f('ix_instituicoes_tipo'), 'instituicoes', ['tipo'], unique=False)
    op.create_table('legislaturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camara_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.String(length=50), nullable=True),
    sa.Column('data_fim', sa.String(length=50), nullable=True),
    sa.Column('ano_inicio', sa.Integer(), nullable=True),
    sa.Column('ano_fim', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legislaturas_camara_id'), 'legislaturas', ['camara_id'], unique=True)
    op.create_index(op.f('ix_legislaturas_id'), 'legislaturas', ['id'], unique=False)
    op.create_index(op.f('ix_legislaturas_numero'), 'legislaturas', ['numero'], unique=True)
    op.create_table('cargos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instituicao_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('fonte', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['instituicao_id'], ['instituicoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cargos_id'), 'cargos', ['id'], unique=False)
    op.create_index(op.f('ix_cargos_instituicao_id'), 'cargos', ['instituicao_id'], unique=False)
    op.create_table('filiacoes_partidarias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deputado_id', sa.Integer(), nullable=False),
    sa.Column('sigla_partido', sa.String(length=50), nullable=False),
    sa.Column('nome_partido', sa.String(length=150), nullable=True),
    sa.Column('data_inicio', sa.String(length=50), nullable=True),
    sa.Column('data_fim', sa.String(length=50), nullable=True),
    sa.Column('fonte', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['deputado_id'], ['deputados.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filiacoes_partidarias_deputado_id'), 'filiacoes_partidarias', ['deputado_id'], unique=False)
    op.create_index(op.f('ix_filiacoes_partidarias_id'), 'filiacoes_partidarias', ['id'], unique=False)
    op.create_index(op.f('ix_filiacoes_partidarias_sigla_partido'), 'filiacoes_partidarias', ['sigla_partido'], unique=False)
    op.create_table('mandatos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deputado_id', sa.Integer(), nullable=False),
    sa.Column('legislatura_id', sa.Integer(), nullable=True),
    sa.Column('legislatura_numero', sa.Integer(), nullable=True),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('sigla_partido', sa.String(length=50), nullable=True),
    sa.Column('uf', sa.String(length=10), nullable=True),
    sa.Column('situacao', sa.String(length=100), nullable=True),
    sa.Column('condicao_eleitoral', sa.String(length=100), nullable=True),
    sa.Column('data_inicio', sa.String(length=50), nullable=True),
    sa.Column('data_fim', sa.String(length=50), nullable=True),
    sa.Column('dados_raw', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['deputado_id'], ['deputados.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['legislatura_id'], ['legislaturas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mandatos_deputado_id'), 'mandatos', ['deputado_id'], unique=False)
    op.create_index(op.f('ix_mandatos_id'), 'mandatos', ['id'], unique=False)
    op.create_index(op.f('ix_mandatos_legislatura_id'), 'mandatos', ['legislatura_id'], unique=False)
    op.create_index(op.f('ix_mandatos_legislatura_numero'), 'mandatos', ['legislatura_numero'], unique=False)
    op.create_index(op.f('ix_mandatos_sigla_partido'), 'mandatos', ['sigla_partido'], unique=False)
    op.create_index(op.f('ix_mandatos_situacao'), 'mandatos', ['situacao'], unique=False)
    op.create_index(op.f('ix_mandatos_uf'), 'mandatos', ['uf'], unique=False)
    op.create_table('relacoes_institucionais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instituicao_origem_id', sa.Integer(), nullable=False),
    sa.Column('instituicao_destino_id', sa.Integer(), nullable=False),
    sa.Column('tipo_relacao', sa.String(length=50), nullable=False),
    sa.Column('data_inicio', sa.String(length=50), nullable=True),
    sa.Column('data_fim', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('fonte', sa.String(length=150), nullable=True),
    sa.Column('url_fonte', sa.String(length=500), nullable=True),
    sa.Column('dados_raw', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['instituicao_destino_id'], ['instituicoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instituicao_origem_id'], ['instituicoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relacoes_institucionais_id'), 'relacoes_institucionais', ['id'], unique=False)
    op.create_index(op.f('ix_relacoes_institucionais_instituicao_destino_id'), 'relacoes_institucionais', ['instituicao_destino_id'], unique=False)
    op.create_index(op.f('ix_relacoes_institucionais_instituicao_origem_id'), 'relacoes_institucionais', ['instituicao_origem_id'], unique=False)
    op.create_index(op.f('ix_relacoes_institucionais_tipo_relacao'), 'relacoes_institucionais', ['tipo_relacao'], unique=False)
    op.create_table('ocupacoes_cargo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cargo_id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=True),
    sa.Column('nome_ocupante', sa.String(length=255), nullable=False),
    sa.Column('data_inicio', sa.String(length=50), nullable=True),
    sa.Column('data_fim', sa.String(length=50), nullable=True),
    sa.Column('fonte', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pessoa_id'], ['deputados.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocupacoes_cargo_cargo_id'), 'ocupacoes_cargo', ['cargo_id'], unique=False)
    op.create_index(op.f('ix_ocupacoes_cargo_id'), 'ocupacoes_cargo', ['id'], unique=False)
    op.create_index(op.f('ix_ocupacoes_cargo_pessoa_id'), 'ocupacoes_cargo', ['pessoa_id'], unique=False)
    op.create_index(op.f('ix_deputado_historico_deputado_id'), 'deputado_historico', ['deputado_id'], unique=False)
    op.create_index(op.f('ix_deputados_situacao'), 'deputados', ['situacao'], unique=False)
    op.create_index(op.f('ix_evento_deputados_deputado_id'), 'evento_deputados', ['deputado_id'], unique=False)
    op.create_index(op.f('ix_evento_deputados_evento_id'), 'evento_deputados', ['evento_id'], unique=False)
    op.create_index(op.f('ix_proposicao_autores_deputado_id'), 'proposicao_autores', ['deputado_id'], unique=False)
    op.create_index(op.f('ix_proposicao_autores_proposicao_id'), 'proposicao_autores', ['proposicao_id'], unique=False)
    op.create_index(op.f('ix_proposicao_temas_proposicao_id'), 'proposicao_temas', ['proposicao_id'], unique=False)
    op.create_index(op.f('ix_proposicao_temas_tema_id'), 'proposicao_temas', ['tema_id'], unique=False)
    op.create_index(op.f('ix_tramitacoes_proposicao_id'), 'tramitacoes', ['proposicao_id'], unique=False)
    op.create_index(op.f('ix_votacao_orientacoes_votacao_id'), 'votacao_orientacoes', ['votacao_id'], unique=False)
    op.create_index(op.f('ix_votacao_proposicoes_proposicao_id'), 'votacao_proposicoes', ['proposicao_id'], unique=False)
    op.create_index(op.f('ix_votacao_proposicoes_votacao_id'), 'votacao_proposicoes', ['votacao_id'], unique=False)
    op.add_column('votos', sa.Column('sigla_partido_momento', sa.String(length=50), nullable=True))
    op.add_column('votos', sa.Column('uf_momento', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_votos_deputado_id'), 'votos', ['deputado_id'], unique=False)
    op.create_index(op.f('ix_votos_votacao_id'), 'votos', ['votacao_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votos_votacao_id'), table_name='votos')
    op.drop_index(op.f('ix_votos_deputado_id'), table_name='votos')
    op.drop_column('votos', 'uf_momento')
    op.drop_column('votos', 'sigla_partido_momento')
    op.drop_index(op.f('ix_votacao_proposicoes_votacao_id'), table_name='votacao_proposicoes')
    op.drop_index(op.f('ix_votacao_proposicoes_proposicao_id'), table_name='votacao_proposicoes')
    op.drop_index(op.f('ix_votacao_orientacoes_votacao_id'), table_name='votacao_orientacoes')
    op.drop_index(op.f('ix_tramitacoes_proposicao_id'), table_name='tramitacoes')
    op.drop_index(op.f('ix_proposicao_temas_tema_id'), table_name='proposicao_temas')
    op.drop_index(op.f('ix_proposicao_temas_proposicao_id'), table_name='proposicao_temas')
    op.drop_index(op.f('ix_proposicao_autores_proposicao_id'), table_name='proposicao_autores')
    op.drop_index(op.f('ix_proposicao_autores_deputado_id'), table_name='proposicao_autores')
    op.drop_index(op.f('ix_evento_deputados_evento_id'), table_name='evento_deputados')
    op.drop_index(op.f('ix_evento_deputados_deputado_id'), table_name='evento_deputados')
    op.drop_index(op.f('ix_deputados_situacao'), table_name='deputados')
    op.drop_index(op.f('ix_deputado_historico_deputado_id'), table_name='deputado_historico')
    op.drop_index(op.f('ix_ocupacoes_cargo_pessoa_id'), table_name='ocupacoes_cargo')
    op.drop_index(op.f('ix_ocupacoes_cargo_id'), table_name='ocupacoes_cargo')
    op.drop_index(op.f('ix_ocupacoes_cargo_cargo_id'), table_name='ocupacoes_cargo')
    op.drop_table('ocupacoes_cargo')
    op.drop_index(op.f('ix_relacoes_institucionais_tipo_relacao'), table_name='relacoes_institucionais')
    op.drop_index(op.f('ix_relacoes_institucionais_instituicao_origem_id'), table_name='relacoes_institucionais')
    op.drop_index(op.f('ix_relacoes_institucionais_instituicao_destino_id'), table_name='relacoes_institucionais')
    op.drop_index(op.f('ix_relacoes_institucionais_id'), table_name='relacoes_institucionais')
    op.drop_table('relacoes_institucionais')
    op.drop_index(op.f('ix_mandatos_uf'), table_name='mandatos')
    op.drop_index(op.f('ix_mandatos_situacao'), table_name='mandatos')
    op.drop_index(op.f('ix_mandatos_sigla_partido'), table_name='mandatos')
    op.drop_index(op.f('ix_mandatos_legislatura_numero'), table_name='mandatos')
    op.drop_index(op.f('ix_mandatos_legislatura_id'), table_name='mandatos')
    op.drop_index(op.f('ix_mandatos_id'), table_name='mandatos')
    op.drop_index(op.f('ix_mandatos_deputado_id'), table_name='mandatos')
    op.drop_table('mandatos')
    op.drop_index(op.f('ix_filiacoes_partidarias_sigla_partido'), table_name='filiacoes_partidarias')
    op.drop_index(op.f('ix_filiacoes_partidarias_id'), table_name='filiacoes_partidarias')
    op.drop_index(op.f('ix_filiacoes_partidarias_deputado_id'), table_name='filiacoes_partidarias')
    op.drop_table('filiacoes_partidarias')
    op.drop_index(op.f('ix_cargos_instituicao_id'), table_name='cargos')
    op.drop_index(op.f('ix_cargos_id'), table_name='cargos')
    op.drop_table('cargos')
    op.drop_index(op.f('ix_legislaturas_numero'), table_name='legislaturas')
    op.drop_index(op.f('ix_legislaturas_id'), table_name='legislaturas')
    op.drop_index(op.f('ix_legislaturas_camara_id'), table_name='legislaturas')
    op.drop_table('legislaturas')
    op.drop_index(op.f('ix_instituicoes_tipo'), table_name='instituicoes')
    op.drop_index(op.f('ix_instituicoes_sigla'), table_name='instituicoes')
    op.drop_index(op.f('ix_instituicoes_poder'), table_name='instituicoes')
    op.drop_index(op.f('ix_instituicoes_nome'), table_name='instituicoes')
    op.drop_index(op.f('ix_instituicoes_nivel_federativo'), table_name='instituicoes')
    op.drop_index(op.f('ix_instituicoes_id'), table_name='instituicoes')
    op.drop_index(op.f('ix_instituicoes_esfera'), table_name='instituicoes')
    op.drop_index(op.f('ix_instituicoes_codigo_externo'), table_name='instituicoes')
    op.drop_table('instituicoes')
    # ### end Alembic commands ###
